OUTPUT_DIR: "checkpoints/exp/"
DATA:
  TRAIN:
    ROOT_DIR: "/media/public/yan1/doublez/realdoubleZ/Data/MVS/train/dtu"
  VAL:
    ROOT_DIR: "/media/public/yan1/doublez/realdoubleZ/Data/MVS/train/dtu"
  TEST:
    ROOT_DIR: "/media/public/yan1/doublez/realdoubleZ/Data/MVS/train/dtu"
    NUM_VIEW: 5
    IMG_HEIGHT: 960
    IMG_WIDTH: 1280
    NUM_VIRTUAL_PLANE: 96
    INTER_SCALE: 2.13
  NUM_WORKERS: 16
MODEL:
  EDGE_CHANNELS: (32, 32, 64)
SCHEDULER:
  TYPE: "StepLR"
  INIT_EPOCH: 4
  MAX_EPOCH: 16
  StepLR:
    gamma: 0.9
    step_size: 2
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.001
  TYPE: 'RMSprop'
TRAIN:
  BATCH_SIZE: 2
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 100
TEST:
  WEIGHT: "outputs/exp/model_pretrained.pth"
  LOG_PERIOD: 1
